version: '3'
services:
  scheduler:
    build: ./
    volumes:
      - ./:/var/www/scheduler

    ports:
      - 3000:3000

    links:
      - mongo

    environment:
      NODE_ENV: development
      SERVER_PORT: 3000
      DB_CONNECTION_STRING: mongodb://mongo:27017/jobs

    command: sh -c 'npm i && npm start'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
