const SCRAPE_WEBSITE = 'scrapeWebsite';
const SEND_WELCOME_EMAILS = 'sendWelcomeEmails';
const SEND_INVOICES = 'sendInvoices';

exports.SCRAPE_WEBSITE = SCRAPE_WEBSITE;
exports.SEND_WELCOME_EMAILS = SEND_WELCOME_EMAILS;
exports.SEND_INVOICES = SEND_INVOICES;

exports.JOB_TYPES = [SCRAPE_WEBSITE, SEND_WELCOME_EMAILS, SEND_INVOICES];
